# Generated by Django 4.2.30 on 2026-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=1000)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen_url', models.CharField(max_length=500)),
                ('url_referencia', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
