# Generated by Django 4.2.30 on 2026-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='imagen_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='url_referencia',
            field=models.TextField(),
        ),
    ]
