# Generated by Django 4.2.30 on 2026-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_comunicado_imagen_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='url_referencia',
            field=models.CharField(max_length=500),
        ),
    ]
